name: Deploy to S3

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install awscli
        run: |
          python3 -m pip install --upgrade pip awscli

      - name: Sync HTML (short cache)
        run: |
          aws s3 cp index.html s3://${{ secrets.S3_BUCKET }}/index.html --acl public-read --cache-control "max-age=3600, must-revalidate" --content-type "text/html"

      - name: Sync assets (long cache)
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }}/ --exclude ".git/*" --exclude ".github/*" --exclude "README.md" \
            --acl public-read \
            --delete \
            --exclude "index.html" \
            --cache-control "max-age=31536000, immutable"
